openapi: 3.0.3
info:
  title: Calculator Service
  description: Service for adding numbers, a Goa teaser
  version: "1.0"
servers:
- url: http://localhost:8000
paths:
  /add/{a}/{b}:
    get:
      tags:
      - calc
      summary: add calc
      operationId: calc#add
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        schema:
          type: integer
          description: Left operand
          example: 5920194056805489328
          format: int64
        example: 8052218409301066017
      - name: b
        in: path
        description: Right operand
        required: true
        schema:
          type: integer
          description: Right operand
          example: 2245842885737722152
          format: int64
        example: 3346131084553893015
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: integer
                example: 6513733567661029654
                format: int64
              example: 3122430129802868656
  /div/{a}/{b}:
    get:
      tags:
      - calc
      summary: divide calc
      description: Divide returns the integral division of two integers.
      operationId: calc#divide
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        schema:
          type: integer
          description: Left operand
          example: 2403877865146434878
          format: int64
        example: 1176453865776169456
      - name: b
        in: path
        description: Right operand
        required: true
        schema:
          type: integer
          description: Right operand
          example: 7751818438486731811
          format: int64
        example: 5283882173996522064
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: integer
                example: 3448989877641388488
                format: int64
              example: 8272531006444625870
        "400":
          description: 'DivByZero: Bad Request response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
  /mul/{a}/{b}:
    get:
      tags:
      - calc
      summary: mul calc
      operationId: calc#mul
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        schema:
          type: integer
          description: Left operand
          example: 2082938806418090480
          format: int64
        example: 817058348830766028
      - name: b
        in: path
        description: Right operand
        required: true
        schema:
          type: integer
          description: Right operand
          example: 3322573843781975777
          format: int64
        example: 499723715072376515
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: integer
                example: 7528159319778012238
                format: int64
              example: 5562130696647899406
  /sub/{a}/{b}:
    get:
      tags:
      - calc
      summary: sub calc
      operationId: calc#sub
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        schema:
          type: integer
          description: Left operand
          example: 5058434971892362792
          format: int64
        example: 6339444414280965279
      - name: b
        in: path
        description: Right operand
        required: true
        schema:
          type: integer
          description: Right operand
          example: 2998957498373416763
          format: int64
        example: 669093391323277721
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: integer
                example: 862594352938458553
                format: int64
              example: 6850943989821012471
components:
  schemas:
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: true
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of
            the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence
            of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: false
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: false
      example:
        id: 3F1FKVRR
        message: Value of ID must be an integer
        name: bad_request
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
tags:
- name: calc
  description: The calc service performs operations on numbers.
